// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: deKwkoK4pA1w3jYaAefVBE
// Component: tu75SPTPNjm57x
import * as React from "react"
import * as p from "@plasmicapp/react-web"
import * as ph from "@plasmicapp/host"
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web"
import Header from "../../Header" // plasmic-import: IZ7cmxqWjCYvg/component
import CaseStudiesWraper from "../../CaseStudiesWraper" // plasmic-import: WpjxXuLMQkn-2l/component
import CtaBottom from "../../CtaBottom" // plasmic-import: q_9J07FjKI49cH/component
import Footer from "../../Footer" // plasmic-import: rUgGjC8cM1U1l/component
import { useScreenVariants as useScreenVariantsrjDmXlLiWnTyry } from "./PlasmicGlobalVariant__Screen" // plasmic-import: rjDmXLLiWNTyry/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css"
import * as projectcss from "./plasmic_netra.module.css" // plasmic-import: deKwkoK4pA1w3jYaAefVBE/projectcss
import * as sty from "./PlasmicStories.module.css" // plasmic-import: tu75SPTPNjm57x/css
import girls18285391920JpgE8O7G209USxCex from "./images/girls18285391920Jpg.jpeg" // plasmic-import: E8O7G209USxCex/picture
import woman32879561920JpgJEAqYrGa2AoOSb from "./images/woman32879561920Jpg.jpeg" // plasmic-import: jEAqYRGa2aoOSb/picture
import girl18484541920JpgYhVJyf0QhMyRvj from "./images/girl18484541920Jpg.jpeg" // plasmic-import: yhVJyf0qhMYRvj/picture
import girl23664381920JpgTTd4LFp4BmPkTm from "./images/girl23664381920Jpg.jpeg" // plasmic-import: TTd4LFp4bmPkTm/picture
import woman31165871920JpgG3NnHcZpmPbkjp from "./images/woman31165871920Jpg.jpeg" // plasmic-import: G3nnHcZPMPbkjp/picture
import girl17750351920JpgThdyxglMtVlhj from "./images/girl17750351920Jpg.jpeg" // plasmic-import: -thdyxglMtVlhj/picture

export const PlasmicStories__VariantProps = new Array()

export const PlasmicStories__ArgProps = new Array()

export const defaultStories__Args = {}

function PlasmicStories__RenderFunc(props) {
  const { variants, overrides, forNode } = props
  const args = Object.assign({}, defaultStories__Args, props.args)
  const $props = args
  const $ctx = ph.useDataEnv?.() || {}
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsrjDmXlLiWnTyry(),
  })

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div
            data-plasmic-name={"pageBanerSection"}
            data-plasmic-override={overrides.pageBanerSection}
            className={classNames(projectcss.all, sty.pageBanerSection)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__k8Ysy)}>
              <h1
                data-plasmic-name={"h1"}
                data-plasmic-override={overrides.h1}
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1
                )}
              >
                {"Stories"}
              </h1>
            </div>
          </div>

          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(projectcss.all, sty.section)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__abj9G)}>
              <div className={classNames(projectcss.all, sty.freeBox__lAoeb)}>
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__cdGen)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"columns"}
                      data-plasmic-override={overrides.columns}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.columns)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__fCs3O
                        )}
                      >
                        <CaseStudiesWraper
                          className={classNames(
                            "__wab_instance",
                            sty.caseStudiesWraper__qrv9K
                          )}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__rkPVt
                        )}
                      >
                        <CaseStudiesWraper
                          className={classNames(
                            "__wab_instance",
                            sty.caseStudiesWraper__k07HY
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__k1UUa)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"auto"}
                            loading={"lazy"}
                            src={{
                              src: girls18285391920JpgE8O7G209USxCex,
                              fullWidth: 1920,
                              fullHeight: 1280,
                              aspectRatio: undefined,
                            }}
                          />
                        </CaseStudiesWraper>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__rjhKm
                        )}
                      >
                        <CaseStudiesWraper
                          className={classNames(
                            "__wab_instance",
                            sty.caseStudiesWraper__tntiT
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__cShqr)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"auto"}
                            loading={"lazy"}
                            src={{
                              src: woman32879561920JpgJEAqYrGa2AoOSb,
                              fullWidth: 1920,
                              fullHeight: 1280,
                              aspectRatio: undefined,
                            }}
                          />
                        </CaseStudiesWraper>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__e08Ij
                        )}
                      >
                        <CaseStudiesWraper
                          className={classNames(
                            "__wab_instance",
                            sty.caseStudiesWraper__cr0Uh
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__bgSzb)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"auto"}
                            loading={"lazy"}
                            src={{
                              src: girl18484541920JpgYhVJyf0QhMyRvj,
                              fullWidth: 1920,
                              fullHeight: 1279,
                              aspectRatio: undefined,
                            }}
                          />
                        </CaseStudiesWraper>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__nSPpe
                        )}
                      >
                        <CaseStudiesWraper
                          className={classNames(
                            "__wab_instance",
                            sty.caseStudiesWraper__unWet
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img___1BZoq)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"auto"}
                            loading={"lazy"}
                            src={{
                              src: girl23664381920JpgTTd4LFp4BmPkTm,
                              fullWidth: 1920,
                              fullHeight: 1280,
                              aspectRatio: undefined,
                            }}
                          />
                        </CaseStudiesWraper>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__dSa29
                        )}
                      >
                        <CaseStudiesWraper
                          className={classNames(
                            "__wab_instance",
                            sty.caseStudiesWraper__nuGyt
                          )}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__weNnO
                        )}
                      >
                        <CaseStudiesWraper
                          className={classNames(
                            "__wab_instance",
                            sty.caseStudiesWraper__vDh1M
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img___2SuTs)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"auto"}
                            loading={"lazy"}
                            src={{
                              src: woman31165871920JpgG3NnHcZpmPbkjp,
                              fullWidth: 1920,
                              fullHeight: 1279,
                              aspectRatio: undefined,
                            }}
                          />
                        </CaseStudiesWraper>
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__xMxGf
                        )}
                      >
                        <CaseStudiesWraper
                          className={classNames(
                            "__wab_instance",
                            sty.caseStudiesWraper__x4PgS
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__wdAo)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"auto"}
                            loading={"lazy"}
                            src={{
                              src: girl17750351920JpgThdyxglMtVlhj,
                              fullWidth: 1920,
                              fullHeight: 1191,
                              aspectRatio: undefined,
                            }}
                          />
                        </CaseStudiesWraper>
                      </div>
                    </p.Stack>
                  </p.Stack>
                ) : null}
              </div>
            </div>
          </section>

          <CtaBottom
            data-plasmic-name={"ctaBottom"}
            data-plasmic-override={overrides.ctaBottom}
            className={classNames("__wab_instance", sty.ctaBottom)}
          />

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </p.Stack>
      </div>
    </React.Fragment>
  )
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "pageBanerSection",
    "h1",
    "section",
    "columns",
    "ctaBottom",
    "footer",
  ],

  header: ["header"],
  pageBanerSection: ["pageBanerSection", "h1"],
  h1: ["h1"],
  section: ["section", "columns"],
  columns: ["columns"],
  ctaBottom: ["ctaBottom"],
  footer: ["footer"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicStories__ArgProps,
      internalVariantPropNames: PlasmicStories__VariantProps,
    })

    return PlasmicStories__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicStories"
  } else {
    func.displayName = `PlasmicStories.${nodeName}`
  }
  return func
}

export const PlasmicStories = Object.assign(
  // Top-level PlasmicStories renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    pageBanerSection: makeNodeComponent("pageBanerSection"),
    h1: makeNodeComponent("h1"),
    section: makeNodeComponent("section"),
    columns: makeNodeComponent("columns"),
    ctaBottom: makeNodeComponent("ctaBottom"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicStories
    internalVariantProps: PlasmicStories__VariantProps,
    internalArgProps: PlasmicStories__ArgProps,
  }
)

export default PlasmicStories
/* prettier-ignore-end */
