// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: deKwkoK4pA1w3jYaAefVBE
// Component: 7_QVl897eB3MHy
import * as React from "react"
import * as p from "@plasmicapp/react-web"
import * as ph from "@plasmicapp/host"
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web"
import Header from "../../Header" // plasmic-import: IZ7cmxqWjCYvg/component
import Testimonial from "../../Testimonial" // plasmic-import: Q16YjPEYk5yNyA/component
import CtaBottom from "../../CtaBottom" // plasmic-import: q_9J07FjKI49cH/component
import Footer from "../../Footer" // plasmic-import: rUgGjC8cM1U1l/component
import { useScreenVariants as useScreenVariantsrjDmXlLiWnTyry } from "./PlasmicGlobalVariant__Screen" // plasmic-import: rjDmXLLiWNTyry/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css"
import * as projectcss from "./plasmic_netra.module.css" // plasmic-import: deKwkoK4pA1w3jYaAefVBE/projectcss
import * as sty from "./PlasmicStory.module.css" // plasmic-import: 7_QVl897eB3MHy/css
import Icon16Icon from "./icons/PlasmicIcon__Icon16" // plasmic-import: Ef5GQ04R83kK-I/icon
import LoactionVectorsvgIcon from "./icons/PlasmicIcon__LoactionVectorsvg" // plasmic-import: KShInrsyWaflUh/icon
import PhoneVectorsvgIcon from "./icons/PlasmicIcon__PhoneVectorsvg" // plasmic-import: RxipPuPCnHkGl7/icon
import EmailVectorsvgIcon from "./icons/PlasmicIcon__EmailVectorsvg" // plasmic-import: WQ52TjU0YmHFxm/icon
import woman32879561920JpgJEAqYrGa2AoOSb from "./images/woman32879561920Jpg.jpeg" // plasmic-import: jEAqYRGa2aoOSb/picture
import people31046351920JpgG7RneH3MEsqQti from "./images/people31046351920Jpg.jpeg" // plasmic-import: g7rneH3MEsqQTI/picture
import girls18285391920JpgE8O7G209USxCex from "./images/girls18285391920Jpg.jpeg" // plasmic-import: E8O7G209USxCex/picture

export const PlasmicStory__VariantProps = new Array()

export const PlasmicStory__ArgProps = new Array()

export const defaultStory__Args = {}

function PlasmicStory__RenderFunc(props) {
  const { variants, overrides, forNode } = props
  const args = Object.assign({}, defaultStory__Args, props.args)
  const $props = args
  const $ctx = ph.useDataEnv?.() || {}
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsrjDmXlLiWnTyry(),
  })

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div
            data-plasmic-name={"pageBanerSection"}
            data-plasmic-override={overrides.pageBanerSection}
            className={classNames(projectcss.all, sty.pageBanerSection)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__od6R8)}>
              <h1
                data-plasmic-name={"h1"}
                data-plasmic-override={overrides.h1}
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1
                )}
              >
                {"Story"}
              </h1>
            </div>
          </div>

          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(projectcss.all, sty.section)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__qwzEq)}>
              <div className={classNames(projectcss.all, sty.freeBox___8S6C6)}>
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__dDi0M)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"foreground"}
                      data-plasmic-override={overrides.foreground}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.foreground)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__iXasZ
                        )}
                      >
                        <h2
                          data-plasmic-name={"h2"}
                          data-plasmic-override={overrides.h2}
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            projectcss.__wab_text,
                            sty.h2
                          )}
                        >
                          {"Story heading"}
                        </h2>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wzoIn
                          )}
                        >
                          {
                            "Vitae sed sem a justo mauris potenti a primis vivamus justo tempor viverra adipiscing convallis fusce odio condimentum mi parturient ultricies. Vitae sed sem a justo mauris potenti a primis vivamus justo tempor viverra adipiscing convallis fusce odio condimentum mi  arturient ultricies. Vitae sed sem a justo mauris potenti a primis vivamus justo  empor viverra adipiscing convallis fusce odio condimentum mi parturient ultricies. Vitae sed sem a justo mauris potenti a primis vivamus justo  empor viverra adipiscing convallis fusce odio condimentum mi parturient ultricies."
                          }
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__kccx5
                          )}
                        >
                          {
                            "Vitae sed sem a justo mauris potenti a primis vivamus justo tempor viverra adipiscing convallis fusce odio condimentum mi parturient ultricies. Vitae sed sem a justo mauris potenti a primis vivamus justo tempor viverra adipiscing convallis fusce odio condimentum mi  arturient ultricies. Vitae sed sem a justo mauris potenti a primis vivamus justo  empor viverra adipiscing convallis fusce odio condimentum mi parturient ultricies. Vitae sed sem a justo mauris potenti a primis vivamus justo  empor viverra adipiscing convallis fusce odio condimentum mi parturient ultricies."
                          }
                        </div>
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__bugqu
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__jGcrT
                          )}
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__bqioa
                            )}
                          >
                            {"Built on capability"}
                          </h3>

                          <Icon16Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__wX0Rd
                            )}
                            role={"img"}
                          />
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__q3TsN
                          )}
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3___1TQ1P
                            )}
                          >
                            {"Highly energetic"}
                          </h3>

                          <Icon16Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__kzv28
                            )}
                            role={"img"}
                          />
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__xiFb
                          )}
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__ppzOg
                            )}
                          >
                            {"100% transparency and accountability"}
                          </h3>

                          <Icon16Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__qYnwm
                            )}
                            role={"img"}
                          />
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__czFLe
                          )}
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__igXr
                            )}
                          >
                            {"Refreshing clarity"}
                          </h3>

                          <Icon16Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__hcVo8
                            )}
                            role={"img"}
                          />
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__c04Wr
                          )}
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__hCojl
                            )}
                          >
                            {"Modern results"}
                          </h3>

                          <Icon16Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__ssBrx
                            )}
                            role={"img"}
                          />
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__tTEs
                          )}
                        >
                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__obAah
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__pE6Ng
                              )}
                            >
                              <LoactionVectorsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__gsO2O
                                )}
                                role={"img"}
                              />
                            </div>

                            <p.Stack
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__nt3Md
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__dRYoM
                                )}
                              >
                                {"121 state lorem state"}
                              </div>
                            </p.Stack>
                          </p.Stack>

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__o5FxX
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__sfdR
                              )}
                            >
                              <PhoneVectorsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__voDke
                                )}
                                role={"img"}
                              />
                            </div>

                            <p.Stack
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__jp2M8
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__chb1R
                                )}
                              >
                                {"888888885588"}
                              </div>
                            </p.Stack>
                          </p.Stack>

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__dZetN
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__hwLpR
                              )}
                            >
                              <EmailVectorsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__rF3J5
                                )}
                                role={"img"}
                              />
                            </div>

                            <p.Stack
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__w1B4
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__eaeY5
                                )}
                              >
                                {"Info@gmail.com"}
                              </div>
                            </p.Stack>
                          </p.Stack>
                        </p.Stack>
                      </p.Stack>
                    </p.Stack>
                  </p.Stack>
                ) : null}
              </div>
            </div>
          </section>

          <div className={classNames(projectcss.all, sty.freeBox__g46Jy)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___3Z5AQ)}
            >
              <Testimonial
                className={classNames("__wab_instance", sty.testimonial__gqA0X)}
                slot={
                  <React.Fragment>
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__hliCb)}
                      displayHeight={"64px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"64px"}
                      src={{
                        src: woman32879561920JpgJEAqYrGa2AoOSb,
                        fullWidth: 1920,
                        fullHeight: 1280,
                        aspectRatio: undefined,
                      }}
                    />

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___7A2Kg
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__gzpvF
                        )}
                      >
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5__lb71U
                          )}
                        >
                          {"Lorem doi"}
                        </h5>
                      </div>
                    </p.Stack>
                  </React.Fragment>
                }
              />

              <Testimonial
                className={classNames(
                  "__wab_instance",
                  sty.testimonial___7B4SM
                )}
                slot={
                  <React.Fragment>
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__pdM)}
                      displayHeight={"64px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"64px"}
                      src={{
                        src: people31046351920JpgG7RneH3MEsqQti,
                        fullWidth: 1920,
                        fullHeight: 1281,
                        aspectRatio: undefined,
                      }}
                    />

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__sgP0U)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___2ThxQ
                        )}
                      >
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5___77CRg
                          )}
                        >
                          {"Lorem doi"}
                        </h5>
                      </div>
                    </p.Stack>
                  </React.Fragment>
                }
              />

              <Testimonial
                className={classNames("__wab_instance", sty.testimonial__ctKm)}
                slot={
                  <React.Fragment>
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__isxoC)}
                      displayHeight={"64px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"64px"}
                      src={{
                        src: girls18285391920JpgE8O7G209USxCex,
                        fullWidth: 1920,
                        fullHeight: 1280,
                        aspectRatio: undefined,
                      }}
                    />

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__z4Tx3)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__kzvfh
                        )}
                      >
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5__rg7I0
                          )}
                        >
                          {"Lorem doi"}
                        </h5>
                      </div>
                    </p.Stack>
                  </React.Fragment>
                }
              />
            </p.Stack>
          </div>

          <CtaBottom
            data-plasmic-name={"ctaBottom"}
            data-plasmic-override={overrides.ctaBottom}
            className={classNames("__wab_instance", sty.ctaBottom)}
          />

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </p.Stack>
      </div>
    </React.Fragment>
  )
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "pageBanerSection",
    "h1",
    "section",
    "foreground",
    "h2",
    "ctaBottom",
    "footer",
  ],

  header: ["header"],
  pageBanerSection: ["pageBanerSection", "h1"],
  h1: ["h1"],
  section: ["section", "foreground", "h2"],
  foreground: ["foreground", "h2"],
  h2: ["h2"],
  ctaBottom: ["ctaBottom"],
  footer: ["footer"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicStory__ArgProps,
      internalVariantPropNames: PlasmicStory__VariantProps,
    })

    return PlasmicStory__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicStory"
  } else {
    func.displayName = `PlasmicStory.${nodeName}`
  }
  return func
}

export const PlasmicStory = Object.assign(
  // Top-level PlasmicStory renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    pageBanerSection: makeNodeComponent("pageBanerSection"),
    h1: makeNodeComponent("h1"),
    section: makeNodeComponent("section"),
    foreground: makeNodeComponent("foreground"),
    h2: makeNodeComponent("h2"),
    ctaBottom: makeNodeComponent("ctaBottom"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicStory
    internalVariantProps: PlasmicStory__VariantProps,
    internalArgProps: PlasmicStory__ArgProps,
  }
)

export default PlasmicStory
/* prettier-ignore-end */
