// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: deKwkoK4pA1w3jYaAefVBE
// Component: 1_AoDTejJueIFc
import * as React from "react"
import * as p from "@plasmicapp/react-web"
import * as ph from "@plasmicapp/host"
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web"
import Header from "../../Header" // plasmic-import: IZ7cmxqWjCYvg/component
import ServicesWhite from "../../ServicesWhite" // plasmic-import: v9iiG2M953HZOc/component
import Footer from "../../Footer" // plasmic-import: rUgGjC8cM1U1l/component
import { useScreenVariants as useScreenVariantsrjDmXlLiWnTyry } from "./PlasmicGlobalVariant__Screen" // plasmic-import: rjDmXLLiWNTyry/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css"
import * as projectcss from "./plasmic_netra.module.css" // plasmic-import: deKwkoK4pA1w3jYaAefVBE/projectcss
import * as sty from "./PlasmicServices.module.css" // plasmic-import: 1_AoDTejJueIFc/css
import woman32879561920JpgJEAqYrGa2AoOSb from "./images/woman32879561920Jpg.jpeg" // plasmic-import: jEAqYRGa2aoOSb/picture

export const PlasmicServices__VariantProps = new Array()

export const PlasmicServices__ArgProps = new Array()

export const defaultServices__Args = {}

function PlasmicServices__RenderFunc(props) {
  const { variants, overrides, forNode } = props
  const args = Object.assign({}, defaultServices__Args, props.args)
  const $props = args
  const $ctx = ph.useDataEnv?.() || {}
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsrjDmXlLiWnTyry(),
  })

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div
            data-plasmic-name={"pageBanerSection"}
            data-plasmic-override={overrides.pageBanerSection}
            className={classNames(projectcss.all, sty.pageBanerSection)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__f5NxD)}>
              <h1
                data-plasmic-name={"h1"}
                data-plasmic-override={overrides.h1}
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1
                )}
              >
                {"Services"}
              </h1>
            </div>
          </div>

          <section className={classNames(projectcss.all, sty.section__k2SNo)}>
            <div className={classNames(projectcss.all, sty.freeBox__yhKNj)}>
              <div className={classNames(projectcss.all, sty.freeBox__w4IPn)}>
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__ywxKe)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.columns__kcZs6)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___7XLw5
                        )}
                      >
                        <ServicesWhite
                          className={classNames(
                            "__wab_instance",
                            sty.servicesWhite__jmAxy
                          )}
                          slot={
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__e9Q2Q
                              )}
                            >
                              {"Services main"}
                            </h3>
                          }
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__wAlGp
                        )}
                      >
                        <ServicesWhite
                          className={classNames(
                            "__wab_instance",
                            sty.servicesWhite__wtJFy
                          )}
                          slot={
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__haotk
                              )}
                            >
                              {"Services main"}
                            </h3>
                          }
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__ulYj6
                        )}
                      >
                        <ServicesWhite
                          className={classNames(
                            "__wab_instance",
                            sty.servicesWhite__qi4Fv
                          )}
                          slot={
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__l678
                              )}
                            >
                              {"Services main"}
                            </h3>
                          }
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__pS0Ds
                        )}
                      >
                        <ServicesWhite
                          className={classNames(
                            "__wab_instance",
                            sty.servicesWhite__oocCz
                          )}
                          slot={
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__jcdKl
                              )}
                            >
                              {"Services main"}
                            </h3>
                          }
                        />
                      </div>

                      <div
                        className={classNames(projectcss.all, sty.column__wlF)}
                      >
                        <ServicesWhite
                          className={classNames(
                            "__wab_instance",
                            sty.servicesWhite__vzreu
                          )}
                          slot={
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__rvSI
                              )}
                            >
                              {"Services main"}
                            </h3>
                          }
                        />
                      </div>

                      <div
                        className={classNames(projectcss.all, sty.column__evKg)}
                      >
                        <ServicesWhite
                          className={classNames(
                            "__wab_instance",
                            sty.servicesWhite___946M4
                          )}
                          slot={
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3___4JBv
                              )}
                            >
                              {"Services main"}
                            </h3>
                          }
                        />
                      </div>
                    </p.Stack>
                  </p.Stack>
                ) : null}
              </div>
            </div>
          </section>

          <section className={classNames(projectcss.all, sty.section__xyqQj)}>
            <h2
              className={classNames(
                projectcss.all,
                projectcss.h2,
                projectcss.__wab_text,
                sty.h2__g8ZU
              )}
            >
              {hasVariant(globalVariants, "screen", "mobileOnly")
                ? "Why Choose Us"
                : "Our process"}
            </h2>

            <div className={classNames(projectcss.all, sty.freeBox___4B144)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__k32Bc)}
              >
                <div className={classNames(projectcss.all, sty.column___8WPEg)}>
                  <ServicesWhite
                    className={classNames(
                      "__wab_instance",
                      sty.servicesWhite__zrXpJ
                    )}
                    slot={
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__xPnlv
                        )}
                      >
                        {"Services main"}
                      </h3>
                    }
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__zMrwu)}>
                  <ServicesWhite
                    className={classNames(
                      "__wab_instance",
                      sty.servicesWhite__rmDhl
                    )}
                    slot={
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__sgV4H
                        )}
                      >
                        {"Services main"}
                      </h3>
                    }
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__gcIWu)}>
                  <ServicesWhite
                    className={classNames(
                      "__wab_instance",
                      sty.servicesWhite__eazlX
                    )}
                    slot={
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3___3LRi
                        )}
                      >
                        {"Services main"}
                      </h3>
                    }
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__rd5Bz)}>
                  <ServicesWhite
                    className={classNames(
                      "__wab_instance",
                      sty.servicesWhite___8RGrM
                    )}
                    slot={
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3___4MPec
                        )}
                      >
                        {"Services main"}
                      </h3>
                    }
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__im2Ld)}>
                  <ServicesWhite
                    className={classNames(
                      "__wab_instance",
                      sty.servicesWhite__x0Wc6
                    )}
                    slot={
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__oywy
                        )}
                      >
                        {"Services main"}
                      </h3>
                    }
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column___8XNr)}>
                  <ServicesWhite
                    className={classNames(
                      "__wab_instance",
                      sty.servicesWhite__vpihg
                    )}
                    slot={
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__oArEk
                        )}
                      >
                        {"Services main"}
                      </h3>
                    }
                  />
                </div>
              </p.Stack>
            </div>
          </section>

          <section className={classNames(projectcss.all, sty.section__cCyt)}>
            <div className={classNames(projectcss.all, sty.freeBox__blvh8)}>
              <div className={classNames(projectcss.all, sty.freeBox__zn3M)}>
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__bbu1I)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.columns__tDyBt)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__gg0U7
                        )}
                      >
                        <ServicesWhite
                          className={classNames(
                            "__wab_instance",
                            sty.servicesWhite__r4OeN
                          )}
                          slot={
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__zl4Vc
                              )}
                            >
                              {"Services main"}
                            </h3>
                          }
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___9Fn2Z
                        )}
                      >
                        <ServicesWhite
                          className={classNames(
                            "__wab_instance",
                            sty.servicesWhite__ablwS
                          )}
                          slot={
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3___1NT4O
                              )}
                            >
                              {"Services main"}
                            </h3>
                          }
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__nonRb
                        )}
                      >
                        <ServicesWhite
                          className={classNames(
                            "__wab_instance",
                            sty.servicesWhite__ei2P
                          )}
                          slot={
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__aNcDh
                              )}
                            >
                              {"Services main"}
                            </h3>
                          }
                        />
                      </div>

                      <div
                        className={classNames(projectcss.all, sty.column__anBi)}
                      >
                        <ServicesWhite
                          className={classNames(
                            "__wab_instance",
                            sty.servicesWhite__uPwUz
                          )}
                          slot={
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__vgRQr
                              )}
                            >
                              {"Services main"}
                            </h3>
                          }
                        />
                      </div>

                      <div
                        className={classNames(projectcss.all, sty.column__h604)}
                      >
                        <ServicesWhite
                          className={classNames(
                            "__wab_instance",
                            sty.servicesWhite___5Y4Yv
                          )}
                          slot={
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3___1Koh2
                              )}
                            >
                              {"Services main"}
                            </h3>
                          }
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__ry6Qe
                        )}
                      >
                        <ServicesWhite
                          className={classNames(
                            "__wab_instance",
                            sty.servicesWhite__cFLt
                          )}
                          slot={
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__jgQj
                              )}
                            >
                              {"Services main"}
                            </h3>
                          }
                        />
                      </div>
                    </p.Stack>
                  </p.Stack>
                ) : null}
              </div>
            </div>
          </section>

          <section className={classNames(projectcss.all, sty.section__keOtX)}>
            <div className={classNames(projectcss.all, sty.freeBox___8Q29T)}>
              <div className={classNames(projectcss.all, sty.freeBox__i4Kae)}>
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___9TmtN)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.columns___6Usvk
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__yljFo
                        )}
                      >
                        <p.PlasmicImg
                          data-plasmic-name={"img"}
                          data-plasmic-override={overrides.img}
                          alt={""}
                          className={classNames(sty.img)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                          src={{
                            src: woman32879561920JpgJEAqYrGa2AoOSb,
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined,
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__mmrNb
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__r2JMq
                          )}
                        >
                          <h2
                            className={classNames(
                              projectcss.all,
                              projectcss.h2,
                              projectcss.__wab_text,
                              sty.h2__fXb0O
                            )}
                          >
                            {"Why Choose Us"}
                          </h2>

                          <div
                            data-plasmic-name={"text"}
                            data-plasmic-override={overrides.text}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam"
                            }
                          </div>

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.columns__m4VZx
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.column__w7Vot
                              )}
                            >
                              <ServicesWhite
                                className={classNames(
                                  "__wab_instance",
                                  sty.servicesWhite___7QFCx
                                )}
                                slot={
                                  <h3
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h3,
                                      projectcss.__wab_text,
                                      sty.h3__mz2D
                                    )}
                                  >
                                    {"Services main"}
                                  </h3>
                                }
                              />
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                sty.column__qkdBd
                              )}
                            >
                              <ServicesWhite
                                className={classNames(
                                  "__wab_instance",
                                  sty.servicesWhite__zyryL
                                )}
                                slot={
                                  <h3
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h3,
                                      projectcss.__wab_text,
                                      sty.h3___60De3
                                    )}
                                  >
                                    {"Services main"}
                                  </h3>
                                }
                              />
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                sty.column__achUv
                              )}
                            >
                              <ServicesWhite
                                className={classNames(
                                  "__wab_instance",
                                  sty.servicesWhite__kLwNl
                                )}
                                slot={
                                  <h3
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h3,
                                      projectcss.__wab_text,
                                      sty.h3__auh1M
                                    )}
                                  >
                                    {"Services main"}
                                  </h3>
                                }
                              />
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                sty.column__ouaw2
                              )}
                            >
                              <ServicesWhite
                                className={classNames(
                                  "__wab_instance",
                                  sty.servicesWhite__ns6Fb
                                )}
                                slot={
                                  <h3
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.h3,
                                      projectcss.__wab_text,
                                      sty.h3__dYs5N
                                    )}
                                  >
                                    {"Services main"}
                                  </h3>
                                }
                              />
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </div>
                    </p.Stack>
                  </p.Stack>
                ) : null}
              </div>
            </div>
          </section>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </p.Stack>
      </div>
    </React.Fragment>
  )
}

const PlasmicDescendants = {
  root: ["root", "header", "pageBanerSection", "h1", "img", "text", "footer"],
  header: ["header"],
  pageBanerSection: ["pageBanerSection", "h1"],
  h1: ["h1"],
  img: ["img"],
  text: ["text"],
  footer: ["footer"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicServices__ArgProps,
      internalVariantPropNames: PlasmicServices__VariantProps,
    })

    return PlasmicServices__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicServices"
  } else {
    func.displayName = `PlasmicServices.${nodeName}`
  }
  return func
}

export const PlasmicServices = Object.assign(
  // Top-level PlasmicServices renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    pageBanerSection: makeNodeComponent("pageBanerSection"),
    h1: makeNodeComponent("h1"),
    img: makeNodeComponent("img"),
    text: makeNodeComponent("text"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicServices
    internalVariantProps: PlasmicServices__VariantProps,
    internalArgProps: PlasmicServices__ArgProps,
  }
)

export default PlasmicServices
/* prettier-ignore-end */
